export const article = {
  name: 'Shakespeare',
  created_at: '2024-06-08T16:37:10.076Z',
  published_at: '2024-06-09T13:18:25.599Z',
  id: 508449055,
  uuid: 'feb08a0e-b4ef-4c0c-8d55-a84dd1c1eaa5',
  content: {
    _uid: 'e8f42522-a42d-4372-83fa-bc87c609be9c',
    body: [
      {
        _uid: '1b6bb8f7-01c0-4706-8164-a46bd12cfb7e',
        image: {
          id: 16184267,
          alt: 'placeholder',
          name: '',
          focus: '',
          title: '',
          source: '',
          filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
          copyright: '',
          fieldtype: 'asset',
          meta_data: {
            alt: 'placeholder',
            title: '',
            source: '',
            copyright: '',
          },
          is_private: false,
          is_external_url: false,
        },
        component: 'singleImage',
      },
      {
        _uid: '2d255027-eae2-4981-ae62-f28ecb7528e0',
        text: {
          type: 'doc',
          content: [
            {
              type: 'paragraph',
              content: [
                {
                  text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                  type: 'text',
                  marks: [
                    {
                      type: 'textStyle',
                      attrs: {
                        color: 'rgb(25, 25, 43)',
                      },
                    },
                  ],
                },
              ],
            },
          ],
        },
        align: 'right',
        image: {
          id: 16184267,
          alt: 'placeholder',
          name: '',
          focus: '',
          title: '',
          source: '',
          filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
          copyright: '',
          fieldtype: 'asset',
          meta_data: {
            alt: 'placeholder',
            title: '',
            source: '',
            copyright: '',
          },
          is_private: false,
          is_external_url: false,
        },
        component: 'textImage',
      },
      {
        _uid: '000f0c5c-d5a7-4b30-8e7d-83661b91a48e',
        component: 'doubleImage',
        firstImage: {
          id: 16184267,
          alt: 'placeholder',
          name: '',
          focus: '',
          title: '',
          source: '',
          filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
          copyright: '',
          fieldtype: 'asset',
          meta_data: {
            alt: 'placeholder',
            title: '',
            source: '',
            copyright: '',
          },
          is_private: false,
          is_external_url: false,
        },
        secondImage: {
          id: 16184267,
          alt: 'placeholder',
          name: '',
          focus: '',
          title: '',
          source: '',
          filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
          copyright: '',
          fieldtype: 'asset',
          meta_data: {
            alt: 'placeholder',
            title: '',
            source: '',
            copyright: '',
          },
          is_private: false,
          is_external_url: false,
        },
      },
      {
        _uid: '68821618-1a08-4e8f-a390-f982e640c55b',
        text: {
          type: 'doc',
          content: [
            {
              type: 'paragraph',
              content: [
                {
                  text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                  type: 'text',
                  marks: [
                    {
                      type: 'textStyle',
                      attrs: {
                        color: 'rgb(25, 25, 43)',
                      },
                    },
                  ],
                },
              ],
            },
          ],
        },
        align: 'left',
        component: 'text',
      },
      {
        _uid: 'c9037719-3448-4496-b96b-1c389d48c192',
        component: 'tripleImage',
        firstImage: {
          id: 16184267,
          alt: 'placeholder',
          name: '',
          focus: '',
          title: '',
          source: '',
          filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
          copyright: '',
          fieldtype: 'asset',
          meta_data: {
            alt: 'placeholder',
            title: '',
            source: '',
            copyright: '',
          },
          is_private: false,
          is_external_url: false,
        },
        thirdImage: {
          id: 16184267,
          alt: 'placeholder',
          name: '',
          focus: '',
          title: '',
          source: '',
          filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
          copyright: '',
          fieldtype: 'asset',
          meta_data: {
            alt: 'placeholder',
            title: '',
            source: '',
            copyright: '',
          },
          is_private: false,
          is_external_url: false,
        },
        secondImage: {
          id: 16184267,
          alt: 'placeholder',
          name: '',
          focus: '',
          title: '',
          source: '',
          filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
          copyright: '',
          fieldtype: 'asset',
          meta_data: {
            alt: 'placeholder',
            title: '',
            source: '',
            copyright: '',
          },
          is_private: false,
          is_external_url: false,
        },
      },
    ],
    meta: [
      {
        _uid: '24c76b34-61aa-4b08-82bd-aa1e1302b0cc',
        title: 'Lumistra - Shakespeare in the Parks 2024',
        component: 'meta',
        transitionTitle: 'Shakespeare in the Parks 2024',
      },
    ],
    headline: [
      {
        _uid: '3f811812-db89-43b3-b9eb-80af54dda7a3',
        cover: {
          id: 16184267,
          alt: 'placeholder',
          name: '',
          focus: '',
          title: '',
          source: '',
          filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
          copyright: '',
          fieldtype: 'asset',
          meta_data: {
            alt: 'placeholder',
            title: '',
            source: '',
            copyright: '',
          },
          is_private: false,
          is_external_url: false,
        },
        title: 'Shakespeare in the Parks 2024',
        author: 'Lumistra',
        component: 'headline',
        publishedAt: '2024-06-08 12:00',
      },
    ],
    component: 'article',
    recommended: [
      {
        name: 'Design for digital age',
        created_at: '2024-06-08T16:39:24.018Z',
        published_at: '2024-06-09T13:18:27.681Z',
        id: 508449068,
        uuid: 'b5e3f8bb-888f-488f-93a3-cbc929d87c47',
        content: {
          _uid: 'e8f42522-a42d-4372-83fa-bc87c609be9c',
          body: [
            {
              _uid: '1b6bb8f7-01c0-4706-8164-a46bd12cfb7e',
              image: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              component: 'singleImage',
            },
            {
              _uid: '2d255027-eae2-4981-ae62-f28ecb7528e0',
              text: {
                type: 'doc',
                content: [
                  {
                    type: 'paragraph',
                    content: [
                      {
                        text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                        type: 'text',
                        marks: [
                          {
                            type: 'textStyle',
                            attrs: {
                              color: 'rgb(25, 25, 43)',
                            },
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              align: 'right',
              image: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              component: 'textImage',
            },
            {
              _uid: '000f0c5c-d5a7-4b30-8e7d-83661b91a48e',
              component: 'doubleImage',
              firstImage: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              secondImage: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
            },
            {
              _uid: '68821618-1a08-4e8f-a390-f982e640c55b',
              text: {
                type: 'doc',
                content: [
                  {
                    type: 'paragraph',
                    content: [
                      {
                        text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                        type: 'text',
                        marks: [
                          {
                            type: 'textStyle',
                            attrs: {
                              color: 'rgb(25, 25, 43)',
                            },
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              align: 'left',
              component: 'text',
            },
            {
              _uid: 'c9037719-3448-4496-b96b-1c389d48c192',
              component: 'tripleImage',
              firstImage: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              thirdImage: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              secondImage: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
            },
          ],
          meta: [
            {
              _uid: '24c76b34-61aa-4b08-82bd-aa1e1302b0cc',
              title: 'Lumistra - Design for digital age',
              component: 'meta',
              transitionTitle: 'Design for digital age',
            },
          ],
          headline: [
            {
              _uid: '3f811812-db89-43b3-b9eb-80af54dda7a3',
              cover: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              title: 'Design for digital age',
              author: 'Lumistra',
              component: 'headline',
              publishedAt: '2024-06-08 12:00',
            },
          ],
          component: 'article',
          recommended: [
            {
              name: 'Shakespeare',
              created_at: '2024-06-08T16:37:10.076Z',
              published_at: '2024-06-09T13:18:25.599Z',
              id: 508449055,
              uuid: 'feb08a0e-b4ef-4c0c-8d55-a84dd1c1eaa5',
              content: {
                _uid: 'e8f42522-a42d-4372-83fa-bc87c609be9c',
                body: [
                  {
                    _uid: '1b6bb8f7-01c0-4706-8164-a46bd12cfb7e',
                    image: {
                      id: 16184267,
                      alt: 'placeholder',
                      name: '',
                      focus: '',
                      title: '',
                      source: '',
                      filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                      copyright: '',
                      fieldtype: 'asset',
                      meta_data: {
                        alt: 'placeholder',
                        title: '',
                        source: '',
                        copyright: '',
                      },
                      is_private: false,
                      is_external_url: false,
                    },
                    component: 'singleImage',
                  },
                  {
                    _uid: '2d255027-eae2-4981-ae62-f28ecb7528e0',
                    text: {
                      type: 'doc',
                      content: [
                        {
                          type: 'paragraph',
                          content: [
                            {
                              text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                              type: 'text',
                              marks: [
                                {
                                  type: 'textStyle',
                                  attrs: {
                                    color: 'rgb(25, 25, 43)',
                                  },
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    align: 'right',
                    image: {
                      id: 16184267,
                      alt: 'placeholder',
                      name: '',
                      focus: '',
                      title: '',
                      source: '',
                      filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                      copyright: '',
                      fieldtype: 'asset',
                      meta_data: {
                        alt: 'placeholder',
                        title: '',
                        source: '',
                        copyright: '',
                      },
                      is_private: false,
                      is_external_url: false,
                    },
                    component: 'textImage',
                  },
                  {
                    _uid: '000f0c5c-d5a7-4b30-8e7d-83661b91a48e',
                    component: 'doubleImage',
                    firstImage: {
                      id: 16184267,
                      alt: 'placeholder',
                      name: '',
                      focus: '',
                      title: '',
                      source: '',
                      filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                      copyright: '',
                      fieldtype: 'asset',
                      meta_data: {
                        alt: 'placeholder',
                        title: '',
                        source: '',
                        copyright: '',
                      },
                      is_private: false,
                      is_external_url: false,
                    },
                    secondImage: {
                      id: 16184267,
                      alt: 'placeholder',
                      name: '',
                      focus: '',
                      title: '',
                      source: '',
                      filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                      copyright: '',
                      fieldtype: 'asset',
                      meta_data: {
                        alt: 'placeholder',
                        title: '',
                        source: '',
                        copyright: '',
                      },
                      is_private: false,
                      is_external_url: false,
                    },
                  },
                  {
                    _uid: '68821618-1a08-4e8f-a390-f982e640c55b',
                    text: {
                      type: 'doc',
                      content: [
                        {
                          type: 'paragraph',
                          content: [
                            {
                              text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                              type: 'text',
                              marks: [
                                {
                                  type: 'textStyle',
                                  attrs: {
                                    color: 'rgb(25, 25, 43)',
                                  },
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    align: 'left',
                    component: 'text',
                  },
                  {
                    _uid: 'c9037719-3448-4496-b96b-1c389d48c192',
                    component: 'tripleImage',
                    firstImage: {
                      id: 16184267,
                      alt: 'placeholder',
                      name: '',
                      focus: '',
                      title: '',
                      source: '',
                      filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                      copyright: '',
                      fieldtype: 'asset',
                      meta_data: {
                        alt: 'placeholder',
                        title: '',
                        source: '',
                        copyright: '',
                      },
                      is_private: false,
                      is_external_url: false,
                    },
                    thirdImage: {
                      id: 16184267,
                      alt: 'placeholder',
                      name: '',
                      focus: '',
                      title: '',
                      source: '',
                      filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                      copyright: '',
                      fieldtype: 'asset',
                      meta_data: {
                        alt: 'placeholder',
                        title: '',
                        source: '',
                        copyright: '',
                      },
                      is_private: false,
                      is_external_url: false,
                    },
                    secondImage: {
                      id: 16184267,
                      alt: 'placeholder',
                      name: '',
                      focus: '',
                      title: '',
                      source: '',
                      filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                      copyright: '',
                      fieldtype: 'asset',
                      meta_data: {
                        alt: 'placeholder',
                        title: '',
                        source: '',
                        copyright: '',
                      },
                      is_private: false,
                      is_external_url: false,
                    },
                  },
                ],
                meta: [
                  {
                    _uid: '24c76b34-61aa-4b08-82bd-aa1e1302b0cc',
                    title: 'Lumistra - Shakespeare in the Parks 2024',
                    component: 'meta',
                    transitionTitle: 'Shakespeare in the Parks 2024',
                  },
                ],
                headline: [
                  {
                    _uid: '3f811812-db89-43b3-b9eb-80af54dda7a3',
                    cover: {
                      id: 16184267,
                      alt: 'placeholder',
                      name: '',
                      focus: '',
                      title: '',
                      source: '',
                      filename: 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                      copyright: '',
                      fieldtype: 'asset',
                      meta_data: {
                        alt: 'placeholder',
                        title: '',
                        source: '',
                        copyright: '',
                      },
                      is_private: false,
                      is_external_url: false,
                    },
                    title: 'Shakespeare in the Parks 2024',
                    author: 'Lumistra',
                    component: 'headline',
                    publishedAt: '2024-06-08 12:00',
                  },
                ],
                component: 'article',
                recommended: [
                  'b5e3f8bb-888f-488f-93a3-cbc929d87c47',
                ],
              },
              slug: 'shakespeare',
              full_slug: 'en/articles/shakespeare',
              sort_by_date: null,
              position: 0,
              tag_list: [],
              is_startpage: false,
              parent_id: 508449028,
              meta_data: null,
              group_id: '8fe61393-2805-4152-8725-5673618c1c67',
              first_published_at: '2024-06-08T16:38:55.931Z',
              release_id: null,
              lang: 'default',
              path: 'articles/shakespeare',
              alternates: [],
              default_full_slug: null,
              translated_slugs: null,
              _stopResolving: true,
            },
          ],
        },
        slug: 'design-for-digital-age',
        full_slug: 'en/articles/design-for-digital-age',
        sort_by_date: null,
        position: 0,
        tag_list: [],
        is_startpage: false,
        parent_id: 508449028,
        meta_data: null,
        group_id: 'f9443792-10a0-41b7-bf3d-b71ba44c3537',
        first_published_at: '2024-06-08T16:38:55.931Z',
        release_id: null,
        lang: 'default',
        path: 'articles/design-for-digital-age',
        alternates: [],
        default_full_slug: null,
        translated_slugs: null,
        _stopResolving: true,
      },
    ],
  },
  slug: 'shakespeare',
  full_slug: 'en/articles/shakespeare',
  sort_by_date: null,
  position: 0,
  tag_list: [],
  is_startpage: false,
  parent_id: 508449028,
  meta_data: null,
  group_id: '8fe61393-2805-4152-8725-5673618c1c67',
  first_published_at: '2024-06-08T16:38:55.931Z',
  release_id: null,
  lang: 'default',
  path: 'articles/shakespeare',
  alternates: [],
  default_full_slug: null,
  translated_slugs: null,
};
