export const lab = {
  name: 'Lab',
  created_at: '2026-05-09T21:21:49.241Z',
  published_at: null,
  updated_at: '2026-05-09T21:25:07.218Z',
  id: 174784959495236,
  uuid: '550f4646-d64b-4d06-bc5e-0141f138dd27',
  content: {
    _uid: '63a1c599-5589-43be-af32-c76b3a226858',
    body: [
      {
        _uid: '9bfb2ebb-5a1e-4af9-a882-796a7a58a015',
        title: 'Lab',
        styling: [
          {
            css: 'section_id > div {\n  margin-top: 100px;\n  margin-bottom: 100px;\n}\n\n@media screen and (max-width: 991px) {\n  section_id > div {\n    margin-top: 80px;\n    margin-bottom: 80px;\n  }\n}',
            _uid: 'd044d9cf-c4a6-4019-ad08-b363e350f6b5',
            component: 'styling',
            _editable: '<!--#storyblok#{"name": "styling", "space": "286844", "uid": "d044d9cf-c4a6-4019-ad08-b363e350f6b5", "id": "174784959495236"}-->',
          },
        ],
        component: 'aboutSection',
        paragraph: {
          type: 'doc',
          content: [
            {
              type: 'paragraph',
              attrs: {
                textAlign: null,
              },
              content: [
                {
                  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porttitor accumsan nisi ac efficitur. Morbi luctus, sapien ac hendrerit accumsan, turpis quam dapibus lorem, vel bibendum sem felis sit amet eros.',
                  type: 'text',
                },
              ],
            },
          ],
        },
        _editable: '<!--#storyblok#{"name": "aboutSection", "space": "286844", "uid": "9bfb2ebb-5a1e-4af9-a882-796a7a58a015", "id": "174784959495236"}-->',
      },
      {
        _uid: '90c29a4c-19d9-44c2-958f-eb048ed27d79',
        items: [
          {
            id: 163416667743304,
            alt: 'ESILUX European Strategy Institute Luxembourg white logo overlaid on a dark navy aerial cityscape of Luxembourg',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg?dim=/2560x1440/' : 'https://a.storyblok.com/f/286844/2560x1440/11b2b82f46/esilux-case-2.webp',
            copyright: 'Studio Lumistra',
            fieldtype: 'asset',
            meta_data: {
              alt: 'ESILUX European Strategy Institute Luxembourg white logo overlaid on a dark navy aerial cityscape of Luxembourg',
              title: '',
              source: '',
              copyright: 'Studio Lumistra',
            },
          },
          {
            id: 163416667759694,
            alt: 'ESILUX logo construction diagram on black background showing spacing rules, grid proportions, and Geist typeface specifications for Security and Defence division',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg?dim=/1280x1440/' : 'https://a.storyblok.com/f/286844/1280x1440/1a074123f0/esilux-case-14.webp',
            copyright: 'Studio Lumistra',
            fieldtype: 'asset',
            meta_data: {
              alt: 'ESILUX logo construction diagram on black background showing spacing rules, grid proportions, and Geist typeface specifications for Security and Defence division',
              title: '',
              source: '',
              copyright: 'Studio Lumistra',
            },
          },
          {
            id: 63507637959391,
            alt: 'tasting notes, coffee+chicken logo on white background',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg?dim=/2560x1440/' : 'https://a.storyblok.com/f/286844/2560x1440/d90c88f4c3/tn-1.webp',
            copyright: 'Studio Lumistra',
            fieldtype: 'asset',
            meta_data: {
              alt: 'tasting notes, coffee+chicken logo on white background',
              title: '',
              source: '',
              copyright: 'Studio Lumistra',
            },
          },
          {
            id: 63507637955294,
            alt: 'Two people holding coffee cups, showing hands and partial view of clothing',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg?dim=/1280x1440/' : 'https://a.storyblok.com/f/286844/1280x1440/82e6d4ee3d/tn-4.webp',
            copyright: '',
            fieldtype: 'asset',
            meta_data: {
              alt: 'Two people holding coffee cups, showing hands and partial view of clothing',
              title: '',
              source: '',
              copyright: '',
            },
          },
          {
            id: 23039344,
            alt: 'Illustrative diagram showcasing font details for Sigma branding, with zoomed-in elements of Japanese characters and a partial English alphabet.',
            name: '',
            focus: '',
            title: '',
            source: 'https://www.stockholmdesignlab.se/work/sigma',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg?dim=/1920x1080/' : 'https://a.storyblok.com/f/286844/1920x1080/43bffefae9/sigma-sdl-1.webp',
            copyright: 'Stockholm Design Lab',
            fieldtype: 'asset',
            meta_data: {
              alt: 'Illustrative diagram showcasing font details for Sigma branding, with zoomed-in elements of Japanese characters and a partial English alphabet.',
              title: '',
              source: 'https://www.stockholmdesignlab.se/work/sigma',
              copyright: 'Stockholm Design Lab',
            },
          },
          {
            id: 23039340,
            alt: "Stack of four Sigma product boxes, including a 'Contemporary 45mm F2.8 DG' lens box and a 'BF Camera' box, in shades of gold, green, grey, and blue.",
            name: '',
            focus: '',
            title: '',
            source: 'https://www.stockholmdesignlab.se/work/sigma',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg?dim=/1920x1920/' : 'https://a.storyblok.com/f/286844/1920x1920/64e430df7b/sigma-sdl-4.webp',
            copyright: 'Stockholm Design Lab',
            fieldtype: 'asset',
            meta_data: {
              alt: "Stack of four Sigma product boxes, including a 'Contemporary 45mm F2.8 DG' lens box and a 'BF Camera' box, in shades of gold, green, grey, and blue.",
              title: '',
              source: 'https://www.stockholmdesignlab.se/work/sigma',
              copyright: 'Stockholm Design Lab',
            },
          },
          {
            id: 63507637943004,
            alt: "Back view of a person wearing a white t-shirt with 'Tasting Notes coffee + chicken' logo",
            name: '2560x1440',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/2560x1440/1281975e27/tn-8.webp',
            copyright: 'Studio Lumistra',
            fieldtype: 'asset',
            meta_data: {
              alt: "Back view of a person wearing a white t-shirt with 'Tasting Notes coffee + chicken' logo",
              title: '',
              source: '',
              copyright: 'Studio Lumistra',
            },
          },
          {
            id: null,
            alt: null,
            name: '2560x1440',
            focus: null,
            title: null,
            source: null,
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://www.dropbox.com/scl/fi/ks465dylz9ba1ovf4ckxl/ESILUX-Explainer2-Animation.mp4?rlkey=43lafggu2d80clpedgmihu78l&st=b8ou1rs2&raw=1',
            copyright: null,
            fieldtype: 'asset',
            meta_data: {},
            is_external_url: true,
          },
        ],
        styling: [],
        component: 'lab',
        _editable: '<!--#storyblok#{"name": "lab", "space": "286844", "uid": "90c29a4c-19d9-44c2-958f-eb048ed27d79", "id": "174784959495236"}-->',
      },
    ],
    meta: [
      {
        _uid: 'f78dd067-3e8d-4a9d-8592-d13607468077',
        email: 'info@studiolumistra.com',
        title: 'Lumistra  - Creative Design Studio',
        author: 'Lumistra',
        keywords: '',
        component: 'meta',
        description: 'Creative design studio transforming sparks and ideas into brands and experiences.',
        transitionTitle: '',
        _editable: '<!--#storyblok#{"name": "meta", "space": "286844", "uid": "f78dd067-3e8d-4a9d-8592-d13607468077", "id": "174784959495236"}-->',
      },
    ],
    component: 'page',
    _editable: '<!--#storyblok#{"name": "page", "space": "286844", "uid": "63a1c599-5589-43be-af32-c76b3a226858", "id": "174784959495236"}-->',
  },
  slug: 'lab',
  full_slug: 'en/lab',
  sort_by_date: null,
  position: -10,
  tag_list: [],
  is_startpage: false,
  parent_id: 486576085,
  meta_data: null,
  group_id: 'a7e39729-d80d-4f27-b015-054c4598844e',
  first_published_at: null,
  release_id: null,
  lang: 'default',
  path: null,
  alternates: [],
  default_full_slug: null,
  translated_slugs: null,
};
