export const project = {
  name: 'Apiar',
  created_at: '2024-06-11T18:51:20.530Z',
  published_at: '2024-06-22T15:35:28.679Z',
  id: 509565006,
  uuid: '0965ab45-c79c-41a6-8ef7-0c9592c77882',
  content: {
    _uid: '95d59f1d-e685-4d83-8f29-b0600aff8e39',
    body: [{
      _uid: '64b6015b-c26e-4097-9e01-2d96744dd3c2',
      image: {
        id: 16209241,
        alt: 'Apiar-CaseStudy-3',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/9f7015e142/apiar-case-3.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-3',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'singleImage',
    }, {
      _uid: 'b52243f4-6d6c-46ed-954f-b5458400576e',
      image: {
        id: 16209238,
        alt: 'Apiar-CaseStudy-4',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/61e93f76fa/apiar-case-4.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-4',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'singleImage',
    }, {
      _uid: 'bf5928a8-8da1-4daf-a3c0-784de6372085',
      image: {
        id: 16209250,
        alt: 'Apiar-CaseStudy-5',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/72fe504e31/apiar-case-5.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-5',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'singleImage',
    }, {
      _uid: '16884b36-d7ca-4fab-a0fd-e8dbbc55ffe4',
      component: 'doubleImage',
      firstImage: {
        id: 16196485,
        alt: 'Apiar-CaseStudy-6',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/960x1080/af6bc02311/apiar-case-6.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-6',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      secondImage: {
        id: 16209254,
        alt: 'Apiar-CaseStudy-7',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/960x1080/c91ef84f62/apiar-case-7.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-7',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
    }, {
      _uid: 'f8371909-489c-4042-bc2d-e2e210fd01f3',
      image: {
        id: 16209255,
        alt: 'Apiar-CaseStudy-8',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/3b33119bf7/apiar-case-8.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-8',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'singleImage',
    }, {
      _uid: '2c887e4d-bc96-4151-bc77-113dfb675e2d',
      image: {
        id: 16196484,
        alt: 'Apiar-CaseStudy-9',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/03731a5436/apiar-case-9.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-9',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'singleImage',
    }, {
      _uid: '4d8ff001-c1d9-4536-a16c-4fb4f8469a5d',
      image: {
        id: 16209257,
        alt: 'Apiar-CaseStudy-10',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/de7741ae31/apiar-case-10.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-10',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'singleImage',
    }, {
      _uid: '57c1fdbc-751d-4e8f-b505-296f138925fd',
      text: {
        type: 'doc',
        content: [{
          type: 'paragraph',
          content: [{
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            type: 'text',
            marks: [{
              type: 'textStyle',
              attrs: {
                color: 'rgb(0, 0, 0)',
              },
            }],
          }],
        }],
      },
      align: 'right',
      image: {
        id: 16196483,
        alt: 'Apiar-CaseStudy-11',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/960x1080/6eb9870be7/apiar-case-11.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-11',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'textImage',
    }, {
      _uid: '41aeee56-acef-484d-a49c-a2aa4db86530',
      image: {
        id: 16196476,
        alt: 'Apiar-CaseStudy-12',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/219df57ef4/apiar-case-12.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-12',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'singleImage',
    }, {
      _uid: '63099ef6-91a6-4ae7-9b37-284d094691c4',
      component: 'doubleImage',
      firstImage: {
        id: 16196487,
        alt: 'Apiar-CaseStudy-14',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/960x1080/7a0174fbe6/apiar-case-14.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-14',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      secondImage: {
        id: 16196486,
        alt: 'Apiar-CaseStudy-13',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/960x1080/dc82775b8b/apiar-case-13.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-13',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
    }, {
      _uid: 'b8d9f2b7-7c6f-4f1f-9314-ed58f1c9056d',
      image: {
        id: 16209259,
        alt: 'Apiar-CaseStudy-15',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/fb3fde5826/apiar-case-15.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-15',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'singleImage',
    }, {
      _uid: 'd1ad9b7d-fce6-4ff2-8bb6-c04bfa52c063',
      image: {
        id: 16196472,
        alt: 'Apiar-CaseStudy-16',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/76d68b3e5c/apiar-case-16.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-16',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'singleImage',
    }, {
      _uid: 'c99cfc2c-a664-467c-b137-cae70478fc76',
      image: {
        id: 16196474,
        alt: 'Apiar-CaseStudy-17',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/44d03ee310/apiar-case-17.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-17',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'singleImage',
    }, {
      _uid: '4665330e-2e48-4297-90d4-06ac6643ebf6',
      image: {
        id: 16196479,
        alt: 'Apiar-CaseStudy-18',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/03af98256d/apiar-case-18.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-18',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      component: 'singleImage',
    }],
    meta: [{
      _uid: 'b9355e30-2ac9-4407-9709-ac129fce26dd',
      title: 'Lumistra - Apiar',
      component: 'meta',
      transitionTitle: 'Apiar',
    }],
    overview: [{
      _uid: 'a3778165-74c7-4622-8030-c960349dd40a',
      cover: {
        id: 16196432,
        alt: 'Apiar-CaseStudy-1',
        name: '',
        focus: '',
        title: '',
        source: '',
        filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/1920x1080/3440567a13/apiar-case-1.webp',
        copyright: '',
        fieldtype: 'asset',
        meta_data: {
          alt: 'Apiar-CaseStudy-1',
          title: '',
          source: '',
          copyright: '',
        },
        is_private: false,
        is_external_url: false,
      },
      title: 'Apiar',
      component: 'overview',
      paragraph: {
        type: 'doc',
        content: [{
          type: 'heading',
          attrs: {
            level: 1,
          },
          content: [{
            text: 'Heading 1',
            type: 'text',
          }],
        }, {
          type: 'heading',
          attrs: {
            level: 2,
          },
          content: [{
            text: 'Heading 2',
            type: 'text',
          }],
        }, {
          type: 'heading',
          attrs: {
            level: 3,
          },
          content: [{
            text: 'Heading 3',
            type: 'text',
          }],
        }, {
          type: 'heading',
          attrs: {
            level: 4,
          },
          content: [{
            text: 'Heading 4',
            type: 'text',
          }],
        }, {
          type: 'heading',
          attrs: {
            level: 5,
          },
          content: [{
            text: 'Heading 5',
            type: 'text',
          }],
        }, {
          type: 'heading',
          attrs: {
            level: 6,
          },
          content: [{
            text: 'Heading 6',
            type: 'text',
          }],
        }, {
          type: 'paragraph',
          content: [{
            text: 'Paragraph',
            type: 'text',
          }],
        }, {
          type: 'bullet_list',
          content: [{
            type: 'list_item',
            content: [{
              type: 'paragraph',
              content: [{
                text: 'Unordered list 1',
                type: 'text',
              }],
            }],
          }, {
            type: 'list_item',
            content: [{
              type: 'paragraph',
              content: [{
                text: 'Unordered list 2',
                type: 'text',
              }],
            }],
          }],
        }, {
          type: 'paragraph',
        }, {
          type: 'ordered_list',
          attrs: {
            order: 1,
          },
          content: [{
            type: 'list_item',
            content: [{
              type: 'paragraph',
              content: [{
                text: 'Ordered list 1',
                type: 'text',
              }],
            }],
          }, {
            type: 'list_item',
            content: [{
              type: 'paragraph',
              content: [{
                text: 'Ordered list 2',
                type: 'text',
              }],
            }],
          }],
        }, {
          type: 'blockquote',
          content: [{
            type: 'paragraph',
            content: [{
              text: 'Quote',
              type: 'text',
            }],
          }],
        }, {
          type: 'paragraph',
          content: [{
            text: 'Link text',
            type: 'text',
            marks: [{
              type: 'link',
              attrs: {
                href: 'https://www.google.com',
                uuid: null,
                anchor: null,
                target: '_self',
                linktype: 'url',
              },
            }],
          }],
        }, {
          type: 'paragraph',
          content: [{
            text: ' ',
            type: 'text',
          }, {
            type: 'emoji',
            attrs: {
              name: 'grinning',
              emoji: '😀',
              fallbackImage: 'https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f600.png',
            },
          }, {
            text: ' ',
            type: 'text',
          }],
        }, {
          type: 'paragraph',
          content: [{
            text: 'bold',
            type: 'text',
            marks: [{
              type: 'bold',
            }],
          }],
        }, {
          type: 'paragraph',
          content: [{
            text: 'italic',
            type: 'text',
            marks: [{
              type: 'italic',
            }],
          }],
        }, {
          type: 'paragraph',
          content: [{
            text: 'italic bold',
            type: 'text',
            marks: [{
              type: 'bold',
            }, {
              type: 'italic',
            }],
          }],
        }, {
          type: 'paragraph',
          content: [{
            text: 'strike through',
            type: 'text',
            marks: [{
              type: 'strike',
            }],
          }],
        }, {
          type: 'paragraph',
          content: [{
            text: 'underline',
            type: 'text',
            marks: [{
              type: 'underline',
            }],
          }],
        }, {
          type: 'paragraph',
          content: [{
            text: 'text color',
            type: 'text',
            marks: [{
              type: 'textStyle',
              attrs: {
                color: '#0000E8',
              },
            }],
          }],
        }],
      },
    }],
    component: 'project',
    recommended: {
      name: 'Spika',
      created_at: '2024-06-08T16:34:59.710Z',
      published_at: '2024-06-09T13:18:56.544Z',
      id: 508449050,
      uuid: '1771be2d-0ac7-4e0f-a43d-827d7b82d874',
      content: {
        _uid: '4bbb1726-7b59-4244-801b-faf8b0750eff',
        body: [{
          _uid: '61055f3e-d5d7-4fdc-ae3f-e00ad4e9b082',
          image: {
            id: 16184267,
            alt: 'placeholder',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
            copyright: '',
            fieldtype: 'asset',
            meta_data: {
              alt: 'placeholder',
              title: '',
              source: '',
              copyright: '',
            },
            is_private: false,
            is_external_url: false,
          },
          component: 'singleImage',
        },
        {
          _uid: '3c9149f6-8889-4579-b08d-9ce5149970ed',
          text: {
            type: 'doc',
            content: [{
              type: 'paragraph',
              content: [{
                text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                type: 'text',
                marks: [{
                  type: 'textStyle',
                  attrs: {
                    color: 'rgb(25, 25, 43)',
                  },
                }],
              }],
            }],
          },
          align: 'right',
          image: {
            id: 16184267,
            alt: 'placeholder',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
            copyright: '',
            fieldtype: 'asset',
            meta_data: {
              alt: 'placeholder',
              title: '',
              source: '',
              copyright: '',
            },
            is_private: false,
            is_external_url: false,
          },
          component: 'textImage',
        },
        {
          _uid: '38f10469-3ea8-4fcb-8e38-09ca1cba61c9',
          component: 'doubleImage',
          firstImage: {
            id: 16184267,
            alt: 'placeholder',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
            copyright: '',
            fieldtype: 'asset',
            meta_data: {
              alt: 'placeholder',
              title: '',
              source: '',
              copyright: '',
            },
            is_private: false,
            is_external_url: false,
          },
          secondImage: {
            id: 16184267,
            alt: 'placeholder',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
            copyright: '',
            fieldtype: 'asset',
            meta_data: {
              alt: 'placeholder',
              title: '',
              source: '',
              copyright: '',
            },
            is_private: false,
            is_external_url: false,
          },
        },
        {
          _uid: '1d8fdc5f-2900-4d16-a0ef-53279984d5e7',
          text: {
            type: 'doc',
            content: [{
              type: 'paragraph',
              content: [{
                text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                type: 'text',
                marks: [{
                  type: 'textStyle',
                  attrs: {
                    color: 'rgb(25, 25, 43)',
                  },
                }],
              }],
            }],
          },
          align: 'left',
          component: 'text',
        },
        {
          _uid: '5874299e-1ab4-4ff0-bdd4-a019a9d59e77',
          component: 'tripleImage',
          firstImage: {
            id: 16184267,
            alt: 'placeholder',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
            copyright: '',
            fieldtype: 'asset',
            meta_data: {
              alt: 'placeholder',
              title: '',
              source: '',
              copyright: '',
            },
            is_private: false,
            is_external_url: false,
          },
          thirdImage: {
            id: 16184267,
            alt: 'placeholder',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
            copyright: '',
            fieldtype: 'asset',
            meta_data: {
              alt: 'placeholder',
              title: '',
              source: '',
              copyright: '',
            },
            is_private: false,
            is_external_url: false,
          },
          secondImage: {
            id: 16184267,
            alt: 'placeholder',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
            copyright: '',
            fieldtype: 'asset',
            meta_data: {
              alt: 'placeholder',
              title: '',
              source: '',
              copyright: '',
            },
            is_private: false,
            is_external_url: false,
          },
        },
        ],
        meta: [{
          _uid: '4a6e3e73-f7bc-4279-a4b1-9783864521d7',
          title: 'Lumistra - Spika',
          component: 'meta',
          transitionTitle: 'Spika',
        }],
        overview: [{
          _uid: '1b56a5ad-fd56-4b18-b54c-cb9dce936d1b',
          cover: {
            id: 16184267,
            alt: 'placeholder',
            name: '',
            focus: '',
            title: '',
            source: '',
            filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
            copyright: '',
            fieldtype: 'asset',
            meta_data: {
              alt: 'placeholder',
              title: '',
              source: '',
              copyright: '',
            },
            is_private: false,
            is_external_url: false,
          },
          title: 'Spika',
          component: 'overview',
          paragraph: {
            type: 'doc',
            content: [{
              type: 'paragraph',
              content: [{
                text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                type: 'text',
                marks: [{
                  type: 'textStyle',
                  attrs: {
                    color: 'rgb(25, 25, 43)',
                  },
                }],
              }],
            }],
          },
        }],
        component: 'project',
        recommended: [{
          name: 'Apiar',
          created_at: '2024-06-08T15:32:02.378Z',
          published_at: '2024-06-09T15:59:40.883Z',
          id: 508448861,
          uuid: 'f9bdd5c3-ef53-4f69-9ac9-223e2c1cee90',
          content: {
            _uid: '4bbb1726-7b59-4244-801b-faf8b0750eff',
            body: [{
              _uid: '61055f3e-d5d7-4fdc-ae3f-e00ad4e9b082',
              image: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              component: 'singleImage',
            },
            {
              _uid: '3c9149f6-8889-4579-b08d-9ce5149970ed',
              text: {
                type: 'doc',
                content: [{
                  type: 'paragraph',
                  content: [{
                    text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                    type: 'text',
                    marks: [{
                      type: 'textStyle',
                      attrs: {
                        color: 'rgb(25, 25, 43)',
                      },
                    }],
                  }],
                }],
              },
              align: 'right',
              image: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              component: 'textImage',
            },
            {
              _uid: '38f10469-3ea8-4fcb-8e38-09ca1cba61c9',
              component: 'doubleImage',
              firstImage: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              secondImage: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
            },
            {
              _uid: '1d8fdc5f-2900-4d16-a0ef-53279984d5e7',
              text: {
                type: 'doc',
                content: [{
                  type: 'paragraph',
                  content: [{
                    text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                    type: 'text',
                    marks: [{
                      type: 'textStyle',
                      attrs: {
                        color: 'rgb(25, 25, 43)',
                      },
                    }],
                  }],
                }],
              },
              align: 'left',
              component: 'text',
            },
            {
              _uid: '5874299e-1ab4-4ff0-bdd4-a019a9d59e77',
              component: 'tripleImage',
              firstImage: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              thirdImage: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              secondImage: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
            },
            ],
            meta: [{
              _uid: '4a6e3e73-f7bc-4279-a4b1-9783864521d7',
              title: 'Lumistra - Apiar',
              component: 'meta',
              transitionTitle: 'Apiar',
            }],
            overview: [{
              _uid: '1b56a5ad-fd56-4b18-b54c-cb9dce936d1b',
              cover: {
                id: 16184267,
                alt: 'placeholder',
                name: '',
                focus: '',
                title: '',
                source: '',
                filename: process.env.mockApi ? '/assets/svg/placeholder.svg' : 'https://a.storyblok.com/f/286844/564x531/c0b7a2f889/placeholder.svg',
                copyright: '',
                fieldtype: 'asset',
                meta_data: {
                  alt: 'placeholder',
                  title: '',
                  source: '',
                  copyright: '',
                },
                is_private: false,
                is_external_url: false,
              },
              title: 'Apiar',
              component: 'overview',
              paragraph: {
                type: 'doc',
                content: [{
                  type: 'paragraph',
                  content: [{
                    text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
                    type: 'text',
                    marks: [{
                      type: 'textStyle',
                      attrs: {
                        color: 'rgb(25, 25, 43)',
                      },
                    }],
                  }],
                }],
              },
            }],
            component: 'project',
            recommended: '1771be2d-0ac7-4e0f-a43d-827d7b82d874',
          },
          slug: 'apiar',
          full_slug: 'en/work/apiar',
          sort_by_date: null,
          position: 10,
          tag_list: [],
          is_startpage: false,
          parent_id: 508448857,
          meta_data: null,
          group_id: 'f145a00d-a39b-4de9-8ae6-288709316cff',
          first_published_at: '2024-06-08T16:35:15.662Z',
          release_id: null,
          lang: 'default',
          path: 'work/apiar',
          alternates: [],
          default_full_slug: null,
          translated_slugs: null,
          _stopResolving: true,
        }],
      },
      slug: 'spika',
      full_slug: 'en/work/spika',
      sort_by_date: null,
      position: 20,
      tag_list: [],
      is_startpage: false,
      parent_id: 508448857,
      meta_data: null,
      group_id: '989ac38f-7bf5-47ab-b31d-c33a90dbd361',
      first_published_at: '2024-06-08T16:35:36.891Z',
      release_id: null,
      lang: 'default',
      path: 'work/spika',
      alternates: [],
      default_full_slug: null,
      translated_slugs: null,
      _stopResolving: true,
    },
  },
  slug: 'apiar',
  full_slug: 'en/work/apiar',
  sort_by_date: null,
  position: 0,
  tag_list: [],
  is_startpage: false,
  parent_id: 508448857,
  meta_data: null,
  group_id: 'b0745623-193c-4601-a2ca-c5816e19d851',
  first_published_at: '2024-06-11T19:44:03.738Z',
  release_id: null,
  lang: 'default',
  path: 'work/apiar',
  alternates: [{
    id: 511438032,
    name: 'Apiar',
    slug: 'apiar',
    published: true,
    full_slug: 'hr/work/apiar',
    is_folder: false,
    parent_id: 509043763,
  }],
  default_full_slug: null,
  translated_slugs: null,
};
