import { sortBy, toLower, uniq } from 'lodash';
import useTranslations from '@/hooks/useTranslations';

function useServices() {
  const { currentLocale, t } = useTranslations();

  const services = () => {
    switch (currentLocale) {
      case 'hr':
        return [
          'dizajn logotipa',
          'logotip',
          'logo',
          'razvoj identiteta brenda',
          'vizualni identitet',
          'identitet brenda',
          'knjiga standarda',
          'brendiranje',
          'razvoj brenda',
          'strategija brenda',
          'dizajn brenda',
          'dizajn posjetnice',
          'dizajn vizitke',
          'vizitka',
          'posjetnica',
          'dizajn brošure',
          'brošura',
          'dizajn letka',
          'letak',
          'dizajn plakata',
          'plakat',
          'dizajn web stranice',
          'web dizajn',
          'web razvoj',
          'web kodiranje',
          'ui/ux dizajn',
          'ui/ux',
          'objave na društvenim mrežama',
          'carousel za društvene mreže',
          'dizajn bannera za društvene mreže',
          'oglas za društvene mreže',
          'dizajn infografike',
          'infografika',
          'dizajn PowerPoint prezentacije',
          'PowerPoint predložak',
          'dizajn predloška',
          'dizajn digitalnog oglasa',
          'digitalni marketing',
          'digitalni oglas',
          'digitalni dizajn',
          'digitalni banneri',
          'dizajn vizuala za tisak',
          'dizajn za tisak',
          'oglas za tisak',
          'dizajn pakiranja',
          'dizajn etikete proizvoda',
          'dizajn etikete',
          'dizajn korica knjige',
          'ilustracija korica knjige',
          'dizajn e-knjige',
          'dizajn izgleda časopisa',
          'dizajn naslovnice',
          'idizajn biltena',
          'predložak biltena',
          'dizajn web bannera',
          'dizajn tiskanog bannera',
          'ilustracija',
          'ui/ux dizajn za mobilne aplikacije',
          'ui/ux dizajn za web aplikacije',
          'dizajn seta ikonica',
          'ikonografija',
          'ikonice',
          'dizajn predloška za email bilten',
          'dizajn natpisa',
          'dizajn jelovnika',
          'dizajn godišnjeg izvješća',
          'dizajn štanda za sajmove',
          'dizajn naljepnice za vozila',
          'dizajn omota za CD/DVD',
          'dizajn vinila',
          'dizajn pozivnice',
          'dizajn čestitke',
          'dizajn životopisa',
          'dizajn portfelja',
          'izrada mockupa za proizvode',
          'dizajn majica',
          'dizajn odjeće',
          'dizajn plakata za velike formate',
          'okolišne grafike',
          'dizajn murala',
          'tipografija',
          'dizajn memoranduma',
          'dizajn omotnice',
          'dizajn natpisa za maloprodaju',
          'dizajn naljepnica',
          'istraživanje i analiza',
          'pozicioniranje brenda',
          'narativ brenda',
          'komunikacija',
          'strategija sadržaja',
          'strategija dizajna',
          'digitalna strategija',
          'strategija za društvene mreže',
          'imenovanje',
          'vizualni identitet',
          'verbalni identitet',
          'dizajn animacije',
          'pakiranje i etiketa',
          'publikacije',
          'umjetnost i ilustracija',
          'dizajn interakcije',
          'sustavi digitalnog dizajna',
          'digitalno prototipiranje',
          'marketinški materijali',
          'kreativni oglas',
          'dizajn aplikacija',
          'kreativni sadržaj za društvene mreže',
          'dizajn prezentacije',
          'priča o brendu',
          'oglašavanje',
          'roba',
          'urednički dizajn',
          'društvene mreže',
          'natpisi',
        ];

      default:
        return [
          'logo design',
          'logo',
          'logotype',
          'logomark',
          'brand identity development',
          'brand identity',
          'brand guidelines',
          'branding',
          'brand development',
          'branding strategy',
          'brand design',
          'business card design',
          'business card',
          'brochure design',
          'brochure',
          'flyer design',
          'flyer',
          'poster design',
          'poster',
          'website design',
          'web design',
          'web development',
          'web coding',
          'ui/ux design',
          'ui/ux',
          'landing page design',
          'landing page development',
          'social media post graphics',
          'social media posts',
          'social media carousel',
          'social media banner design',
          'social media ad',
          'infographic design',
          'infographic',
          'PowerPoint presentation design',
          'PowerPoint template',
          'template design',
          'digital advertisement design',
          'digital marketing',
          'digital ad',
          'digital design',
          'digital banners',
          'print advertisement design',
          'design for print',
          'visuals for print',
          'ad for print',
          'packaging design',
          'packaging',
          'product label design',
          'label design',
          'book cover design',
          'book cover illustration',
          'booklet design',
          'ebook design',
          'magazine layout design',
          'layout design',
          'layout template',
          'layout',
          'newsletter design',
          'newsletter template',
          'web banner design',
          'print banner design',
          'custom illustration',
          'illustration',
          'ui/ux design for mobile apps',
          'ui/ux design for web apps',
          'icon set design',
          'iconography',
          'icons',
          'email newsletter template design',
          'signage design',
          'menu design ',
          'annual report design',
          'trade show booth design',
          'vehicle wrap design',
          'CD/DVD cover design',
          'vinyl design',
          'invitation design',
          'greeting card design',
          'resume design',
          'portfolio design',
          'mockup creation for products',
          't-shirt design',
          'apparel design',
          'poster for large format printing',
          'environmental graphics',
          'mural design',
          'custom typography design',
          'typography',
          'letterhead design',
          'envelope design',
          'retail signage design',
          'sticker design',
          'research & analysis',
          'brand positioning',
          'brand narrative',
          'communication',
          'content strategy',
          'design strategy',
          'digital strategy',
          'social media strategy',
          'naming',
          'visual identity',
          'verbal identity',
          'motion design',
          'packaging & label',
          'publications',
          'art & illustration',
          'interaction design',
          'digital design systems',
          'digital prototyping',
          'website design',
          'marketing materials',
          'ad creative',
          'app design',
          'social media creative',
          'presentation design',
          'brand story',
          'advertising',
          'merchandise',
          'editorial design',
          'social media',
          'signage',
        ];
    }
  };

  const brandStrategy = () => {
    switch (currentLocale) {
      case 'hr':
        return [];
      default:
        return [
          'Research & analisys',
          'Brand positioning',
          'Brand narrative',
          'Communication',
          'Content strategy',
          'Design strategy',
          'Digital strategy',
          'Social media strategy',
          'Naming',
        ];
    }
  };

  const brandDesign = () => {
    switch (currentLocale) {
      case 'hr':
        return [];
      default:
        return [
          'Visual identity',
          'Verbal identity',
          'Motion design',
          'Packaging & label',
          'Publications',
          'Typography',
          'Illustration',
          'Brand guidelines',
          'Art & illustration',
        ];
    }
  };

  const digitalDesign = () => {
    switch (currentLocale) {
      case 'hr':
        return [];
      default:
        return [
          'UX/UI design',
          'Interaction design',
          'Digital design systems',
          'Digital prototyping',
          'Website design',
          'Marketing materials',
          'Ad creative',
          'App design',
          'Social media creative',
          'Presentation design',
        ];
    }
  };

  const brandCommunication = () => {
    switch (currentLocale) {
      case 'hr':
        return [];
      default:
        return [
          'Brand story',
          'Advertising',
          'Merchandise',
          'Editorial Design',
          'Social media',
          'Signage',
        ];
    }
  };

  const groups = {
    brandStrategy: {
      label: t('services.bio.brand_strategy'),
      list: brandStrategy(),
    },
    brandDesign: {
      label: t('services.bio.brand_design'),
      list: brandDesign(),
    },
    digitalDesign: {
      label: t('services.bio.digital_design'),
      list: digitalDesign(),
    },
    brandCommunication: {
      label: t('services.bio.brand_communication'),
      list: brandCommunication(),
    },
  };

  return { services: sortBy(uniq(services()), (service) => toLower(service)), groups };
}

export default useServices;
